"""Expand Exercise model with comprehensive fields from Ejercicios2

Revision ID: 662e96ccb6ec
Revises:
Create Date: 2025-08-06 11:46:54.141456

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "662e96ccb6ec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "client_profiles",
        "sexo",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("MASCULINO", "FEMENINO", name="genderenum"),
        existing_nullable=True,
    )
    op.alter_column(
        "client_profiles",
        "objetivo_entrenamiento",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "AUMENTAR_MASA_MUSCULAR",
            "PERDIDA_DE_PESO",
            "RENDIMIENTO_DEPORTIVO",
            name="traininggoalenum",
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "client_profiles",
        "experiencia",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("BAJA", "MEDIA", "ALTA", name="experienceenum"),
        existing_nullable=True,
    )
    op.alter_column(
        "client_profiles",
        "frecuencia_semanal",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("BAJA", "MEDIA", "ALTA", name="weeklyfrequencyenum"),
        existing_nullable=True,
    )
    op.create_index("idx_client_email", "client_profiles", ["mail"], unique=False)
    op.create_index(
        "idx_client_name", "client_profiles", ["nombre", "apellidos"], unique=False
    )
    op.add_column(
        "exercises", sa.Column("exercise_id", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "exercises", sa.Column("nombre_ingles", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "exercises",
        sa.Column(
            "tipo",
            sa.Enum(
                "MONOARTICULAR", "MULTIARTICULAR", "COMPLEJO", name="exercisetypeenum"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "categoria",
            sa.Enum(
                "BASICO", "INTERMEDIO", "AVANZADO", name="exerciseclassificationenum"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "nivel",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="exerciselevelenum"),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "equipo",
            sa.Enum(
                "BARBELL",
                "DUMBBELL",
                "CABLE",
                "MACHINE",
                "BODYWEIGHT",
                "KETTLEBELL",
                "RESISTANCE_BAND",
                "SMITH_MACHINE",
                "OTHER",
                name="equipmentenum",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "patron_movimiento",
            sa.Enum(
                "KNEE_DOMINANT",
                "HIP_DOMINANT",
                "HORIZONTAL_PUSH",
                "VERTICAL_PUSH",
                "HORIZONTAL_PULL",
                "VERTICAL_PULL",
                "ROTATION",
                "CORE",
                "CARDIO",
                "OTHER",
                name="movementpatternenum",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "tipo_carga",
            sa.Enum("EXTERNAL", "BODYWEIGHT", "RESISTANCE", name="loadtypeenum"),
            nullable=False,
        ),
    )
    op.add_column("exercises", sa.Column("notas", sa.Text(), nullable=True))
    op.alter_column(
        "exercises",
        "musculatura_principal",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises",
        "musculatura_secundaria",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_exercises_nombre"), table_name="exercises")
    op.create_index(op.f("ix_exercises_nombre"), "exercises", ["nombre"], unique=False)
    op.create_index("idx_exercise_categoria", "exercises", ["categoria"], unique=False)
    op.create_index("idx_exercise_equipo", "exercises", ["equipo"], unique=False)
    op.create_index("idx_exercise_id", "exercises", ["exercise_id"], unique=False)
    op.create_index("idx_exercise_nivel", "exercises", ["nivel"], unique=False)
    op.create_index("idx_exercise_nombre", "exercises", ["nombre"], unique=False)
    op.create_index("idx_exercise_tipo", "exercises", ["tipo"], unique=False)
    op.create_index(
        op.f("ix_exercises_exercise_id"), "exercises", ["exercise_id"], unique=True
    )
    op.drop_column("exercises", "tipologia")
    op.drop_column("exercises", "clasificacion")
    op.alter_column(
        "trainers",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "trainers",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "trainers",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "training_routines",
        "frecuencia",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.Enum("BAJA", "MEDIA", "ALTA", name="weeklyfrequencyenum"),
        existing_nullable=False,
    )
    op.alter_column(
        "training_routines",
        "experiencia_requerida",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.Enum("BAJA", "MEDIA", "ALTA", name="experienceenum"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "training_routines",
        "experiencia_requerida",
        existing_type=sa.Enum("BAJA", "MEDIA", "ALTA", name="experienceenum"),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    op.alter_column(
        "training_routines",
        "frecuencia",
        existing_type=sa.Enum("BAJA", "MEDIA", "ALTA", name="weeklyfrequencyenum"),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    op.alter_column(
        "trainers",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "trainers",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "trainers",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.add_column(
        "exercises", sa.Column("clasificacion", sa.VARCHAR(length=10), nullable=False)
    )
    op.add_column(
        "exercises", sa.Column("tipologia", sa.VARCHAR(length=14), nullable=False)
    )
    op.drop_index(op.f("ix_exercises_exercise_id"), table_name="exercises")
    op.drop_index("idx_exercise_tipo", table_name="exercises")
    op.drop_index("idx_exercise_nombre", table_name="exercises")
    op.drop_index("idx_exercise_nivel", table_name="exercises")
    op.drop_index("idx_exercise_id", table_name="exercises")
    op.drop_index("idx_exercise_equipo", table_name="exercises")
    op.drop_index("idx_exercise_categoria", table_name="exercises")
    op.drop_index(op.f("ix_exercises_nombre"), table_name="exercises")
    op.create_index(op.f("ix_exercises_nombre"), "exercises", ["nombre"], unique=1)
    op.alter_column(
        "exercises",
        "musculatura_secundaria",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "exercises",
        "musculatura_principal",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("exercises", "notas")
    op.drop_column("exercises", "tipo_carga")
    op.drop_column("exercises", "patron_movimiento")
    op.drop_column("exercises", "equipo")
    op.drop_column("exercises", "nivel")
    op.drop_column("exercises", "categoria")
    op.drop_column("exercises", "tipo")
    op.drop_column("exercises", "nombre_ingles")
    op.drop_column("exercises", "exercise_id")
    op.drop_index("idx_client_name", table_name="client_profiles")
    op.drop_index("idx_client_email", table_name="client_profiles")
    op.alter_column(
        "client_profiles",
        "frecuencia_semanal",
        existing_type=sa.Enum("BAJA", "MEDIA", "ALTA", name="weeklyfrequencyenum"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "client_profiles",
        "experiencia",
        existing_type=sa.Enum("BAJA", "MEDIA", "ALTA", name="experienceenum"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "client_profiles",
        "objetivo_entrenamiento",
        existing_type=sa.Enum(
            "AUMENTAR_MASA_MUSCULAR",
            "PERDIDA_DE_PESO",
            "RENDIMIENTO_DEPORTIVO",
            name="traininggoalenum",
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "client_profiles",
        "sexo",
        existing_type=sa.Enum("MASCULINO", "FEMENINO", name="genderenum"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
